import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./(site)/globals.css";

import Header from "@/components/header/Header";
import Footer from "@/components/shared/footer/Footer";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          type='text/css'
          charSet='UTF-8'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css'
        />
      </head>
      <body className={dosis.className}>
        <div className='bg-primary text-dark'>
        <Header/>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
